import Head from "next/head";
import { WelcomeScreen } from "../components/welcome-screen/WelcomeScreen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WelcomeScreen />
      </main>
    </div>
  );
}
